services:
  postgres:
    image: postgres:17.5-alpine
    restart: always
    volumes:
      - ./var/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=mydb
    ports:
      - "5432:5432"

  backend:
    build: .
    command: bash -c "alembic upgrade head && uvicorn app.main:app --host 0.0.0.0 --port 8000"
    ports:
      - "8000:8000"
    depends_on:
      - postgres
    env_file: .env
    environment:
      - PG_HOST=postgres
      - PYTHONPATH=/app